name: qr_earth
description: "Plastic Recycle App"
publish_to: "none"
version: 0.3.2+8

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_adaptive_scaffold: ^0.3.1
  flutter_secure_storage: ^9.2.2
  flutter_update_checker: ^0.1.3
  go_router: ^14.3.0
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  loader_overlay: ^4.0.3
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  screen_brightness: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
