name: qr_earth
description: "Plastic Recycle App"
publish_to: "none"
version: 0.2.2+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.1.2
  http: ^1.2.1
  mobile_scanner: ^5.2.1
  qr_flutter: ^4.1.0
  screen_brightness: ^1.0.1
  shared_preferences: ^2.2.3
  upgrader: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
