name: qr_earth
description: "Plastic Recycle App"
publish_to: "none"
version: 0.3.0+6

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_update_checker: ^0.1.3
  go_router: ^14.1.2
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  mobile_scanner: ^5.2.1
  qr_flutter: ^4.1.0
  screen_brightness: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
